version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
  # The Database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql:cached
    environment:
      - 'MYSQL_DATABASE=jiuji-theory'
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - 33061:3306
volumes:
  dbdata:
  nodemodules:
    external: true
