version: '3.7'
services:
  app:
    container_name: jiuji_theory_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - ./prisma/development.env
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: unless-stopped
    tty: true
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
  # The Database
  database:
    container_name: jiuji_theory_database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql:cached
    environment:
      - 'MYSQL_DATABASE=jiuji-theory'
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - 33061:3306
volumes:
  dbdata:
  # nodemodules:
  #   external: true
